spring.application.name=windchill-rest
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

windchill.baseurl=https://pp-2504240936dd.portal.ptc.io//Windchill
windchill.username=pat
{windchill.userpassword=ptc



