spring.application.name=windchill-rest

server.servlet.jsp.init-parameters.development=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


logging.level.com.revy.windchill.*=debug

windchill.baseurl=https://pp-2504240936dd.portal.ptc.io/Windchill/servlet/odata/
#windchill.baseurl=http://plm.revy.com/Windchill
windchill.username=pat
windchill.userpassword=ptc



